name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    environment: dev
    steps:
      - run: |
             echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
             pwd
             ls
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Yarn install
        env:
             NO_FLIPPER: ${{ tst.vars.NO_FLIPPER }}
        run: |
              echo "Yarn install"
              env
      #         yarn install
      # - name: Pod Install
      #   run: |
      #         echo "Pod Install"
      #         env
      #         ls
      #         pwd
      #         cd ios
      #         pod install
      # - name: Check out repository code
      #   uses: yukiarrr/ios-build-action@v1.11.0
      #   with:
      #     project-path: ios/ReactSample.xcodeproj
      #     p12-base64: ${{ secrets.P12_BASE64 }}
      #     mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
      #     code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
      #     team-id: ${{ secrets.TEAM_ID }}
      #     certificate-password: ${{ secrets.PASSWORD }}

